version: "3"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: publify
    expose:
      - 5432
    volumes:
      - /var/lib/postgresql
  auth:
    build: api
    environment:
      FASTAPI_ENV: prod
    ports:
      - 8082
    depends_on:
      - postgres